### ISSUE TITLE
Do not manage /etc/mailname

### ISSUE THREAD

**Issue by davidc** [voxpupuli/puppet-postfix#186]
/etc/mailname is managed on all our systems (including those not running Postfix) through site.pp.

Using this module produces the following error, even if manage_conffiles is false:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/etc/mailname] is already declared in file /etc/puppet/code/environments/production/modules/postfix/manifests/files.pp:31; cannot redeclare at /etc/puppet/code/environments/production/manifests/site.pp:20 at /etc/puppet/code/environments/production/manifests/site.pp:20:3 on node xx

Also there should ideally be a separate flag to not attempt to manage /etc/mailname, since this manage_conffiles flag also affects other important files that *should* be managed.

**Comment by anarcat** [comment]
we also need to *not* manage `/etc/mailname` here, in fact, it should be absent.

**Comment by raphink** [comment]
I'm fine with a flag to not manage it.

**Comment by anarcat** [comment]
actually, looking at the source, it seems there's an undocumented `manage_mailname` setting that does exactly what we need here. maybe this issue should be closed after all.

**Comment by smortex** [comment]
Fixed by #312
