### ISSUE TITLE
Unused smtpd_bind_address parameter on Debian Buster (Postfix 3.4.10)

### ISSUE THREAD

**Issue by sid3windr** [voxpupuli/puppet-postfix#281]
When deploying a configuration with use_amavisd, postconf will throw the following error:

`postconf: warning: /etc/postfix/master.cf: unused parameter: smtpd_bind_address=127.0.0.1`

This configuration option doesn't seem to exist (anymore) - Google doesn't really turn anything up either, apart from people with warnings about this nonexistent parameter for 8+ years...

The "127.0.0.1:10025" service name/port combination already restricts this service to listen on 127.0.0.1 only, so the line can simply be removed from the template.

**Comment by sid3windr** [comment]
Rather than marking it as stale, it would be better to actually fix the issue. Thank you for the wontfix label on all open issues, silly bot.

**Comment by sid3windr** [comment]
No.

**Comment by ekohl** [comment]
In cbece91f81cf227c41a3f38f0157e038f0007721 it was renamed to `smtp_bind_address` so I'm assuming this is fixed.
