### ISSUE TITLE
How to declare a multi-lines parameter ?

### ISSUE THREAD

**Issue by src386** [voxpupuli/puppet-postfix#308]
I can't figure out the correct syntax to pass multi-lines arguments to `postfix::config` (or `::postfix` config). Tried with `@("EOF"/L)`, as a `['list']` or line breaks `\n` .

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.14.1
- Ruby: ruby 2.5.8p224
- Distribution: Ubuntu 18.04
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)

```puppet
class {'::postfix':
  relayhost        => 'foo',
  manage_conffiles => false,
  mta              => true,
  configs          => {
    'smtpd_recipient_restrictions' => {'value' => 
      [
        'permit_mynetworks',
        'reject_unknown_recipient_domain'
      ]
    },
  }
}
```

## What are you seeing

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Postfix::Config[smtpd_recipient_restrictions]: parameter 'value' expects a value of type Undef or String, got Tuple (file: /etc/puppetlabs/code/environments/dev/modules/postfix/manifests/init.pp, line: 159) on node mysrv.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## What behaviour did you expect instead

Here is what I expect to see in `/etc/postfix/main.cf`:

```
smtpd_recipient_restrictions = 
    permit_mynetworks,
    reject_unknown_recipient_domain,
```

## Any additional information you'd like to impart

Works if I pass all parameters in the same line:

```puppet
class {'::postfix':
  relayhost        => 'foo',
  manage_conffiles => false,
  mta              => true,
  configs          => {
    'smtpd_recipient_restrictions' => {'value' => 'permit_mynetworks, reject_unknown_recipient_domain'},
  }
}
```
But this is ugly because I need to pass 7 parameters, resulting in a very long line, in the Puppet code and in the `main.cf` file.

What's the proper syntax to pass multi-lines arguments ?

**Comment by kenyon** [comment]
You can use a heredoc with the `L` switch: https://puppet.com/docs/puppet/7/lang_data_string.html#lang_data_string_heredocs-suppresslinebr

**Comment by OlegPS** [comment]
A bit late I know but if anyone still interested
```
postfix::config {
  'myhostname' : value => 'example.com';
  'smtpd_recipient_restrictions' : value => @("END"/L);
    permit_mynetworks, \
    reject_unknown_recipient_domain
    |- END
  'mynetworks_style' : value => 'host';
}
```
