### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jwe74** [voxpupuli/puppet-postfix#314]
Master branch is ahead of tag v2.0.0 by 19 commits. Can you update the master branch with a newer tag please?

**Comment by kenyon** [comment]
I think this is asking for a new release. See https://voxpupuli.org/docs/releasing_version/ for the release process.

**Comment by jhoblitt** [comment]
@bastelfreak Can we pull the trigger?

**Comment by jcpunk** [comment]
The EL9 fixes from Feb 2022 wills soon become important to me...

**Comment by bastelfreak** [comment]
I just pushed a new release

**Comment by bastelfreak** [comment]
and just as a note: Everybody can create a release PR: https://voxpupuli.org/docs/releasing_version/
