### ISSUE TITLE
Stop managing alias map (/etc/aliases)

### ISSUE THREAD

**Issue by STOIE** [voxpupuli/puppet-postfix#337]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: ANY
- Ruby: ANY
- Distribution: ANY
- Module version: 3.0.0

## How to reproduce (e.g Puppet code you use)

```
  class { '::postfix':
    inet_protocols => 'ipv4',
    smtp_listen => 'all',
    master_entries => ['scan    unix    -               -               n               -               30              smtp -o smtp_send_xforward_command=yes -o disable_mime_output_conversion=yes -o snmp_generic_maps=' ],
  }
  ::postfix::config {
    'mynetworks':  value => 'xxx.xxx.xxx.xxx';
    'masquerade_domains':  value => 'foobar.com';
    'relayhost':  value => "$relayhost, $relayhost2, $relayhost3";
    'content_filter': value => 'scan:127.0.0.1:2525';
    'transport_maps': value => 'hash:/etc/postfix/transport';
    'masquerade_classes': value => 'envelope_sender, header_sender';
    'local_header_rewrite_clients': value => 'static:all';
    'allow_mail_to_files': value => 'alias,forward,include';
    'mydestination': value => '/etc/postfix/destinationlist';
    'relay_domains': value => 'some-domain.com';
    'disable_dns_lookups': value => 'yes';
  }

```

## What are you seeing

`/etc/aliases` is being managed by puppet, I cannot edit the file locally without puppet rewriting it.

## What behaviour did you expect instead

`/etc/aliases` to NOT be managed by puppet and instead be locally managed.

## Output log

NA

## Any additional information you'd like to impart

I have a "somewhat sizeable and advanced" aliases file, and would rather manage it in git directly (locally) rather than in puppet. Is there a way to stop puppet managing that file while still using this puppet module.

**Comment by smortex** [comment]
Looks like we have a parameter for this:
https://github.com/voxpupuli/puppet-postfix/blob/master/REFERENCE.md#manage_aliases

**Comment by STOIE** [comment]
> Looks like we have a parameter for this: https://github.com/voxpupuli/puppet-postfix/blob/master/REFERENCE.md#manage_aliases

Wow - sorry I missed that!
Thank you very much!
