### ISSUE TITLE
v3.0.0 has unmentioned deps

### ISSUE THREAD

**Issue by fayeg21** [voxpupuli/puppet-postfix#341]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.21.0
- Ruby:2.7.7p221
- Distribution: Debian Bulleye
- Module version: 3.0.0

## What are you seeing

Missing desp for puppetlabs-mailalias_core

## What behaviour did you expect instead

The dep to be fullfilled

**Comment by smortex** [comment]
`*_core` modules are bundled in Puppet AIO package, and per se we do not add it to `metadata.json`.
