### ISSUE TITLE
[3.1.0] Add support to puppet 8

### ISSUE THREAD

**Issue by tuxmaster5000** [voxpupuli/puppet-postfix#353]
The camptocamp-augeas dependency must be removed,  because this module is only compatible with the deprecated puppet 6.
See https://forge.puppet.com/modules/camptocamp/augeas/readme
**Puppet >= 4.10.0 < 7.0.0**

**Comment by ekohl** [comment]
In f10082aee7f12f172a42f13ab2bdf8779fb22e71 some lenses were dropped, reducing the need for camptocamp/augeas but 84a211ba40523dda73b64746d60cf585d777727b completely dropped the dependency. Since #358 we already tested with it.
