### ISSUE TITLE
Please add support for Ubuntu 24.04

### ISSUE THREAD

**Issue by sebbASF** [voxpupuli/puppet-postfix#393]
## Affected Puppet, Ruby, OS and module versions/distributions

Ubuntu 24.04

## How to reproduce (e.g Puppet code you use)

classes:
  - postfix::server

## What are you seeing

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Unsupported OS family (file: /etc/puppetlabs/code/environments/test/ext-modules/postfix/manifests/params.pp, line: 89, column: 7)

## What behaviour did you expect instead

No error

**Comment by kenyon** [comment]
You must be using a different Postfix module. There is no such code that would produce this error in this module's `params.pp`: https://github.com/voxpupuli/puppet-postfix/blob/d4058dc4b9d5c00bd27681685e0aa0a81ba1af83/manifests/params.pp

**Comment by kenyon** [comment]
Puppet packages aren't available for Ubuntu noble yet on apt.puppet.com.
